Lint
codesupport/website-frontend pull request #143
Opened 2024-07-13 07:23 UTC by Bashamega

closes #141 
I have upgraded lint and modified the code to be compatible with lint

2024-07-13 10:56 UTC, LamboCreeper reviewed
It doesn't look like you're actually extending `eslint-config-codesupport` anywhere, and our previous config is being completely overwritten?

2024-07-13 10:58 UTC, Bashamega commented
Sorry I forgot. Do you mean something like this: https://eslint.org/docs/latest/extend/shareable-configs

2024-07-29 15:10 UTC, Bashamega commented
@LamboCreeper

2024-07-29 19:10 UTC, LamboCreeper commented
Apologies, I must have missed this. Yes, we have our own package already: https://github.com/codesupport/eslint-config-codesupport

Central code style configuration should be here, so that it can be easily shared across projects.

2024-08-11 10:55 UTC, Bashamega commented
Hello @LamboCreeper :)

Sorry, for the delay. I have updated the config. And everything should be good

2024-08-11 11:25 UTC, LamboCreeper requested changes

2024-08-11 11:25 UTC, LamboCreeper commented on eslint.config.js
> +];
Ironically, this file isn't being linted:
```suggestion
import globals from "globals";
import pluginJs from "@eslint/js";
import tseslint from "typescript-eslint";
import pluginReactConfig from "eslint-plugin-react/configs/recommended.js";

export default [
  { files: ["**/*.{js,mjs,cjs,ts,jsx,tsx}"] },
  { languageOptions: { parserOptions: { ecmaFeatures: { jsx: true } } } },
  { files: ["**/*.js"], languageOptions: { sourceType: "script" } },
  { languageOptions: { globals: globals.browser } },
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
  pluginReactConfig,
];
```

2024-08-11 12:45 UTC, LamboCreeper approved these changes

2024-08-11 12:46 UTC, merged